name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Cache downloaded Towndex documents
        uses: actions/cache@v2
        with:
          path: .towndex/etl-cache
          key: ${{ runner.os }}-
      - uses: towndex/gui-action@v1-beta
        with:
          cache: ./towndex/etl-cache
          input: 1aVqd4ZA9x5z_sP5bCiIO3gOkPMpvydXLx43JNh4Y_2A
          input_format: google_sheets
          output: .
      - name: Build site
        run: yarn build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          cname: www.brunswickunited.org
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
